version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: uwsgi --ini /code/portfolio/django.ini
    volumes:
      - .:/code
    expose:
      - "8001"
    depends_on:
      - db
  nginx:
    image: nginx
    command: bash -c "/usr/sbin/nginx -g 'daemon off;' && chmod 755 -R /var && chmod 400 /etc/nginx/server.key"
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
      - ./nginx/log:/var/log/nginx
      - ./keys/server.crt:/etc/nginx/server.crt
      - ./keys/server.key:/etc/nginx/server.key
    depends_on:
      - web