version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: uwsgi --ini /code/portfolio/django.ini
    volumes:
      - .:/code
    expose:
      - "8001"
    depends_on:
      - db
  nginx:
    image: nginx
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    ports: 
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
      - ./nginx/log:/var/log/nginx
    depends_on:
      - web