# Generated by Django 2.1 on 2019-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=400, null=True, upload_to='image', width_field=600),
        ),
    ]
