# Generated by Django 2.1 on 2019-05-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('career', models.TextField()),
                ('Introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=200)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.SkillCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='work-image')),
                ('description', models.TextField()),
                ('creation_start_date', models.DateField()),
                ('creation_complete_date', models.DateField(null=True)),
            ],
        ),
    ]
