# Generated by Django 2.1 on 2019-05-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
