# Generated by Django 2.2.1 on 2019-06-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.SkillSet')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Work')),
            ],
        ),
    ]
