# Generated by Django 2.2.1 on 2019-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_useskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url_description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
