# Generated by Django 2.2.1 on 2019-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_work_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url_description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
