# Generated by Django 2.2.1 on 2019-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_auto_20190609_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
