# Generated by Django 2.2.1 on 2019-06-23 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_auto_20190609_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='sort_no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
