# Generated by Django 2.2.1 on 2019-06-23 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_skillcategory_sort_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='sort_no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
